### ISSUE TITLE
Egg Minecraft :: Spigot

### ISSUE THREAD

**Issue by Kuroo2021** [matthewpi/images#10]
Java Issue.

container@pterodactyl~ Starting installation process, this could take a few minutes...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  183M  100  183M    0     0  68.7M      0  0:00:02  0:00:02 --:--:-- 97.9M
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3364k  100 3364k    0     0  11.1M      0 --:--:-- --:--:-- --:--:-- 11.2M
Do not use 0 for memory with Java applications. Defaulting to 1024MB.
 WARNING! 1024MB might not be enough to build 1.17+ releases.
[--rev, latest]
Loading BuildTools version: git-BuildTools-a50d932-181 (#181)
Java Version: Java 17
Current Path: /srv
git version 2.39.2
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
Attempting to build version: 'latest' use --rev <version> to override
Found version
{
        "name": "4179",
        "description": "Jenkins build 4179",
        "refs": {
                "BuildData": "32d1baf2f4e0e7cd1ac22c7b2f6eb4c387e8a343",
                "Bukkit": "fa28607adbca047835c8cb0a3faaedbc98e27a71",
                "CraftBukkit": "bdb40c5f107108062b1bb3c40cf5205f54674af6",
                "Spigot": "342f4939f5e80bdeaba2c5303efc80261b8658cf"
        },
        "toolsVersion": 181,
        "javaVersions": [65, 66]
}
*** The version you have requested to build requires Java versions between [Java 21, Java 22], but you are using Java 17
*** Please rerun BuildTools using an appropriate Java version. For obvious reasons outdated MC versions do not support Java versions that did not exist at their release.
 install failed! Attempted to install latest with memory of 1024 and Java version of:
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

**Comment by matthewpi** [comment]
That is not an issue with this repository or any of the images in it. The error message you posted clearly states that Java 21 or 22 is required while you are using Java 17.
